// Postbuild step: emit per-route Open Graph SVG images. Refs #105.
//
// Why SVG (not PNG): zero new dependencies, no native build toolchain.
// Slack / Discord / X handle SVG previews fine; for crawlers that don't,
// the og:title / og:description metadata still gets rendered as a card.
// A missing image is strictly worse than a present-but-unrendered one,
// so SVG is the right floor.
//
// Generation strategy: walk build/ for every prerendered .html, extract
// the <h1> (or fall back to <title>), and emit a 1200x630 SVG at
// build/og/<routePath>.svg using a single dark-themed text-only template.
//
// SeoHead consumes a convention-based default — the og:image URL for any
// route is `${SITE_URL}/og${routePath}.svg` — so every prerendered page
// automatically gets a matching preview without per-route wiring.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const buildDir = resolve(__dirname, '..', 'build');
const ogRoot = resolve(buildDir, 'og');

mkdirSync(ogRoot, { recursive: true });

function* walk(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === '_app') continue;
    if (entry.name === 'og') continue;
    if (entry.name.startsWith('.')) continue;
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else if (entry.name.endsWith('.html')) {
      yield full;
    }
  }
}

function decodeEntities(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&rarr;/g, '→')
    .replace(/&larr;/g, '←')
    .replace(/&mdash;/g, '—')
    .replace(/&ndash;/g, '–')
    .replace(/&hellip;/g, '…')
    .replace(/&nbsp;/g, ' ');
}

function stripTags(s) {
  return s.replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim();
}

function extractMeta(html) {
  // Inner-text extraction is lenient on purpose — these pages are all
  // generated by the same SvelteKit renderer, so the markup is regular.
  const titleM = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const title = titleM ? decodeEntities(stripTags(titleM[1])) : '';
  const h1M = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  const h1 = h1M ? decodeEntities(stripTags(h1M[1])) : '';
  const ledeM = html.match(/<p[^>]*class="[^"]*\b(lede|figure|kicker)\b[^"]*"[^>]*>([\s\S]*?)<\/p>/i);
  const lede = ledeM ? decodeEntities(stripTags(ledeM[2])) : '';
  return { title, h1, lede };
}

/**
 * Wrap text into N lines of at most `maxChars` characters, breaking on
 * spaces. If a word exceeds maxChars it is placed on its own line (we
 * don't hyphenate). Anything past `maxLines` is truncated with an
 * ellipsis on the final line.
 */
function wrap(text, maxChars, maxLines) {
  if (!text) return [];
  const words = text.split(/\s+/).filter(Boolean);
  const lines = [];
  let cur = '';
  for (const w of words) {
    if (lines.length >= maxLines) break;
    const candidate = cur ? cur + ' ' + w : w;
    if (candidate.length <= maxChars) {
      cur = candidate;
      continue;
    }
    if (cur) lines.push(cur);
    cur = w;
  }
  if (cur && lines.length < maxLines) lines.push(cur);
  // Truncate overflow with an ellipsis.
  if (lines.length === maxLines) {
    const remaining = words.slice(lines.join(' ').split(/\s+/).length).length;
    if (remaining > 0) {
      let last = lines[maxLines - 1];
      if (last.length > maxChars - 1) last = last.slice(0, maxChars - 1);
      lines[maxLines - 1] = last + '…';
    }
  }
  return lines;
}

function xmlEscape(s) {
  return String(s).replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c])
  );
}

/**
 * Render the OG SVG. Layout:
 *   - 1200x630 dark canvas
 *   - Top-left brand strap (small caps)
 *   - Heading: up to 3 lines, large, off-white
 *   - Subtitle: 1 line, accent color
 *   - Footer URL
 *
 * Font stack uses widely-installed system fonts; social-card renderers
 * (Chromium-based) resolve them without needing a remote font file.
 */
function renderSvg({ heading, subtitle }) {
  const headingLines = wrap(heading || 'AI Agent Infrastructure Landscape', 26, 3);
  const subLines = wrap(subtitle || '', 60, 1);
  const fontStack =
    'ui-sans-serif, -apple-system, BlinkMacSystemFont, system-ui, Segoe UI, Helvetica, Arial, sans-serif';

  // Vertical layout: brand at y=90, heading block centred around y=300,
  // subtitle at y=480, footer URL at y=580.
  const headingFontSize = headingLines.length <= 1 ? 92 : headingLines.length === 2 ? 80 : 68;
  const headingLineGap = headingFontSize + 12;
  const headingStartY = 280 - ((headingLines.length - 1) * headingLineGap) / 2;

  const headingTspans = headingLines
    .map(
      (l, i) =>
        `<tspan x="60" y="${headingStartY + i * headingLineGap}">${xmlEscape(l)}</tspan>`
    )
    .join('');

  const subtitleBlock = subLines.length
    ? `<text x="60" y="500" fill="#d4845f" font-family="${fontStack}" font-size="30" font-weight="500">${xmlEscape(subLines[0])}</text>`
    : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">
  <rect width="1200" height="630" fill="#0e1116"/>
  <rect x="0" y="0" width="6" height="630" fill="#d4845f"/>
  <text x="60" y="90" fill="#d4845f" font-family="${fontStack}" font-size="22" font-weight="600" letter-spacing="3">AI AGENT INFRASTRUCTURE LANDSCAPE</text>
  <text fill="#f0f0f0" font-family="${fontStack}" font-size="${headingFontSize}" font-weight="700">${headingTspans}</text>
  ${subtitleBlock}
  <text x="60" y="580" fill="#666" font-family="${fontStack}" font-size="18">mrpeppersdev.github.io/agent-infrastructure-landscape</text>
</svg>
`;
}

/**
 * Choose the heading and subtitle for a given parsed page. Preference:
 *   heading  = h1, else <title> with the " — AI Agent…" suffix trimmed
 *   subtitle = lede / figure / kicker text if present and short enough
 */
function pickContent(meta) {
  const heading =
    meta.h1 ||
    meta.title.replace(/\s*[—-]\s*AI Agent.*$/i, '').trim() ||
    'AI Agent Infrastructure Landscape';
  let subtitle = meta.lede || '';
  if (subtitle.length > 120) subtitle = subtitle.slice(0, 117) + '…';
  return { heading, subtitle };
}

const htmlFiles = [...walk(buildDir)];
let written = 0;

for (const file of htmlFiles) {
  const html = readFileSync(file, 'utf8');
  const meta = extractMeta(html);
  const { heading, subtitle } = pickContent(meta);
  const svg = renderSvg({ heading, subtitle });

  // Mirror the route path under build/og/. "/index.html" → "/og/.svg"
  // for the root; "/findings/foo.html" → "/og/findings/foo.svg".
  let rel = file.slice(buildDir.length);
  if (sep !== '/') rel = rel.replaceAll(sep, '/');
  rel = rel.replace(/\/index\.html$/, '/').replace(/\.html$/, '');
  if (rel === '/') rel = '/index';
  const outPath = resolve(ogRoot, rel.slice(1) + '.svg');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, svg);
  written++;
}

console.log(`generate-og: wrote ${written} OG SVG previews under ${ogRoot}`);
