#!/usr/bin/env python3
"""
_staleness_issue_bodies.py — render one markdown body file per flagged row.

Internal helper for .github/workflows/staleness.yml. Reads the JSON list
produced by ``scripts/check_staleness.py`` and writes one ``<i>.md`` plus
one ``<i>.json`` (title + id sidecar) per entry into the output dir. The
workflow's bash loop then dedups by id and calls ``gh issue create``
with ``--body-file``.

Kept in its own file rather than inline-heredoc'd into the YAML because
heredocs inside YAML ``run: |`` blocks introduce indentation surprises
that are easier to dodge than debug. The leading-underscore in the
filename keeps it sorted near other "support" scripts.

Usage:
    python scripts/_staleness_issue_bodies.py <report.json> <output-dir>
"""

from __future__ import annotations

import datetime as dt
import json
import pathlib
import sys


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(
            "usage: _staleness_issue_bodies.py <report.json> <output-dir>",
            file=sys.stderr,
        )
        return 2
    report_path = argv[1]
    body_dir = pathlib.Path(argv[2])
    body_dir.mkdir(parents=True, exist_ok=True)
    with open(report_path, "r", encoding="utf-8") as fh:
        entries = json.load(fh)
    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    for i, e in enumerate(entries):
        body = (
            f"**Row id:** `{e['id']}`\n"
            f"**Name:** {e.get('name', '?')}\n"
            f"**Repo:** {e['repo']}\n"
            f"**Last commit:** {e['last_commit']}\n"
            f"**Days since last commit:** {e['days_since']}\n"
            f"**Severity:** **{e['severity']}** (per MAINTAINER.md §2 freshness SLA)\n"
            f"**Detection signal:** {e['signal']}\n"
            "\n"
            "This issue was opened automatically by the weekly staleness check\n"
            "(`.github/workflows/staleness.yml`, issue #38). The catalog row\n"
            "above hasn't had a meaningful upstream commit within the freshness\n"
            "window — `stale` = 12-24 months quiet, `abandoned` = 24+ months\n"
            "quiet.\n"
            "\n"
            "### Suggested action\n"
            "\n"
            "1. **Verify**. Visit the repo. Is the project genuinely abandoned,\n"
            "   or just quiet because a single maintainer is busy?\n"
            "2. **Update the row.** In `landscape.html` (or wherever the row\n"
            "   lives), update the `latest-release`, `code-release`, and\n"
            "   `status` cells to reflect current reality.\n"
            "3. **Down-tier if needed.** If the project is genuinely dead,\n"
            "   drop it a tier or move it to a historical section. Don't\n"
            "   delete — inbound citations may still reference it.\n"
            "4. **Close this issue** once you've actioned (or explicitly\n"
            "   decided to leave the row as-is with a note).\n"
            "\n"
            "Auto-reopen is not implemented; if upstream resumes activity,\n"
            "this issue stays open until a maintainer closes it manually.\n"
            "\n"
            "---\n"
            "\n"
            f"_Generated by `scripts/check_staleness.py` on {generated_at}._\n"
        )
        (body_dir / f"{i}.md").write_text(body, encoding="utf-8")
        meta = {
            "id": e["id"],
            "title": (
                f"stale-row: {e['id']} ({e['severity']}, "
                f"{e['days_since']}d since last commit)"
            ),
        }
        (body_dir / f"{i}.json").write_text(json.dumps(meta), encoding="utf-8")
    print(
        f"prepared {len(entries)} body files in {body_dir}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
